openapi: 3.0.0
info:
  version: "v0"
  title: SIWFT API Documentation
  description: A Documentation for the SIWFT API
  contact:
    email: "support@siwft.org"
    name: "SIWFT Support"
  license:
    name: "CC BY NC ND 4.0"
    url: "https://creativecommons.org/licenses/by-nc-nd/4.0/"
  termsOfService: "https://siwft.org/terms"
servers:
  - url: https://api.siwft.org
paths:
  /v0/hub/{hubId}/delete:
    delete:
      summary: Delete a wallet Hub
      parameters:
        - in: path
          name: hubId
          description: The Hub ID you want to delete
          required: true
          schema:
            type: string
        - in: header
          name: Authorization
          description: You authorization key of you wallet hub.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully
        '204':
          description: Successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                item:
                  properties:
                    message:
                      type: string
                    code:
                      type: integer
  /v0/hub/{hubId}:
    get:
      summary: Get Hub Information
      description: Get Information's about an specific Wallet Hub. If you want more Information's like the Contact Address or API Key then please specify your API Key in the Header
      parameters:
        - in: path
          name: hubID
          description: The Hub ID you want to get the Information from
          required: true
          schema:
            type: string
        - in: header
          name: Authorization
          description: Your Authorization Key if you want to get all your Wallet Hub Data
          required: false
          schema:
            type: string

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example:
                      true
                  message:
                    type: object
                    properties:
                      name:
                        type: string
                        example: "Your Hub Name"
                      domain:
                        type: string
                        example: "https://domain.tld"
                      contact:
                        type: string
                        format: email
                        example: "contact@domain.tld"
                        description: "'null' in case you didn't provided an Authorization Key"
                      support:
                        type: string
                        format: email
                        example: "support@domain.tld"
                      active:
                        type: boolean
                        example: true
                      apiKey:
                        type: string
                        format: password
                        example: "api_52da990g5bdg0c829db34e8c57568557fg83c524"
                        description: "'null' in case you didn't provided an Authorization Key"
                      created:
                        type: string
                        format: 'date-time'
  /v0/hub/create:
    post:
      summary: Create a new Hub
      description: This endpoint is only accessible for Agents only. If you want to create your own Hub please get in contact with us!
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example:
                    "Your Hub Name"
                domain:
                  type: string
                  example:
                    "domain.tld"
                contact:
                  type: string
                  format: email
                  example:
                    "contact@domain.tld"
                support:
                  type: string
                  format: email
                  example:
                    "support@domain.tld"
              required:
                - name
                - domain
                - contact
                - support
      responses:
        '200':
          description: Hub created successfully
          content:
            application/json:
              schema:
                type: object
                items:
                  properties:
                    success:
                      type: boolean
                    message:
                      type: object
                      items:
                        properties:
                          id:
                            type: integer
                            format: int32
                            example:
                              10000000
                          name:
                            type: string
                            example:
                              "Your Hub Name"
                          domain:
                            type: string
                            example:
                              "https://siwft.org"
                          contact:
                            type: string
                            format: email
                            example:
                              "contact@domain.tld"
                          support:
                            type: string
                            format: email
                            example:
                              "support@domain.tld"
                          active:
                            type: boolean
                            example:
                              true
                          apiKey:
                            type: string
                            example:
                              "api_52da990g5bdg0c829db34e8c57568557fg83c524"
                          created:
                            type: string
                            format: 'date-time'
                            example:
                              "2024-01-10T12:25:36.903Z"