openapi: 3.0.0
info:
  version: "v0"
  title: SIWFT API Documentation
  description: A Documentation for the SIWFT API
  contact:
    email: "support@siwft.org"
    name: "SIWFT Support"
  license:
    name: "CC BY NC ND 4.0"
    url: "https://creativecommons.org/licenses/by-nc-nd/4.0/"
  termsOfService: "https://siwft.org/terms"
servers:
  - url: https://api.siwft.org
paths:
  /v0/transaction/{sender}/{receiver}:
    post:
      summary: Initiate Transaction
      description: "Create a transaction between two parties"

      parameters:
        - in: path
          name: sender
          required: true
          description: "The IWAN from the sender"
          schema:
            type: string
        - in: path
          name: receiver
          required: true
          description: "The receiver IWAN"
          schema:
            type: string
        - in: header
          name: "Authorization"
          required: true
          description: "The authorization key from the sender"
          schema:
            type: string
        - in: header
          name: "X-Auth-Username"
          required: true
          description: "The user name of the sender"
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  format: float
                  example: 13.37
                description:
                  type: string
                  example: "Hello World"
              required:
                - amount
      responses:
        '200':
          description: Transaction successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                    default: false
                  message:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "transaction_34210bja3421834jah6jhh3h67hd34j57bh24301"
                      sender:
                        type: string
                        example: "AT10000000123456789012"
                      receiver:
                        type: string
                        example: "AT10000000098765432112"
                      amount:
                        type: integer
                        format: float
                        example: 13.37
                      description:
                        type: string
                        example: "Hello World"
                      created:
                        type: string
                        format: 'date-time'
  /v0/transaction/:
    get:
      summary: Get own transactions
      description: "Get a list of all your Transactions you made"
      parameters:
        - in: header
          name: "Authorization"
          required: true
          description: "The authorization key from the sender"
          schema:
            type: string
        - in: header
          name: "X-Auth-Username"
          required: true
          description: "The user name of the sender"
          schema:
            type: string
        - in: header
          name: "X-Auth-Iwan"
          required: true
          description: "The users IWAN"
          schema:
            type: string
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                    default: false
                  message:
                    type: array
                    properties:
                      0:
                        type: boolean
                        properties:
                          id:
                            type: string
                            example: "transaction_114e5793868a8480411c73e3d45b6cd7cee8c012"
                          from:
                            type: string
                            example: "AT10000000123456789012"
                          to:
                            type: string
                            example: "AT10000000098765432112"
                          amount:
                            type: integer
                            format: float
                            example: 13.37
                          message:
                            type: string
                            example: "Hello World"
                          date:
                            type: string
                            format: 'date-time'
                          status:
                            type: boolean
                            example: true
                            default: false
                      1:
                        type: boolean
                        properties:
                          id:
                            type: string
                            example: "transaction_114e5793868a8480411c73e3d45b6cd7cee8c012"
                          from:
                            type: string
                            example: "AT10000000123456789012"
                          to:
                            type: string
                            example: "AT10000000098765432112"
                          amount:
                            type: integer
                            format: float
                            example: 13.37
                          message:
                            type: string
                            example: "Hello World"
                          date:
                            type: string
                            format: 'date-time'
                          status:
                            type: boolean
                            example: true
                            default: false
  /v0/transaction/{transactionId}:
    get:
      summary: "Get the Information of a Single Transaction"
      parameters:
        - in: header
          name: "Authorization"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Successful request"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example:
                      true
                    default: false
                  message:
                    type: object
                    properties:
                      message:
                        type: object
                        properties:
                          id:
                            type: string
                            example: "transaction_114e5793868a8480411c73e3d45b6cd7cee8c012"
                          from:
                            type: string
                            example: "AT10000000123456789012"
                          to:
                            type: string
                            example: "AT10000000098765432112"
                          amount:
                            type: integer
                            format: float
                            example: 13.37
                          message:
                            type: string
                            example: "Hello World"
                          date:
                            type: string
                            format: 'date-time'
                          status:
                            type: boolean
                            example: true
                            default: false